id: ADF11B5FC
title: A Daily Practice of Buddha Akṣobhya
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.784322
  last_modified_at: 2022-03-01 00:11:41.784325
