id: ADF11B5FC
title: Prayer for the Land of Great Bliss Practice
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.794220
  last_modified_at: 2022-03-01 00:11:41.794223
