id: ADF11B5FC
title: 'The Swift Steed of Garuḍa, King of Birds: An Instruction for Travelling to
  Sukhāvatī: A Visualization and Recitation of Uṣnīṣa-Sitātapatrā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.801006
  last_modified_at: 2022-03-01 00:11:41.801009
