id: ADF11B5FC
title: A Prayer to the Goddess Parṇaśavarī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.786860
  last_modified_at: 2022-03-01 00:11:41.786863
