id: ADF11B5FC
title: Brief Dhāraṇī of Glorious Vajraṇakhī
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.789148
  last_modified_at: 2022-03-01 00:11:41.789151
