id: ADF11B5FC
title: The Concise Mahāmudrā Preliminaries Arranged for Recitation
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.799910
  last_modified_at: 2022-03-01 00:11:41.799913
