id: ADF11B5FC
title: 'Zabchema: Profound Cure, The Practice of Bhaiṣajya-Guru, Lord of Physicians'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.802062
  last_modified_at: 2022-03-01 00:11:41.802065
