id: ADF11B5FC
title: Brief Smoke Offering to the Great Lion of the World
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.790140
  last_modified_at: 2022-03-01 00:11:41.790142
