id: ADF11B5FC
title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.798934
  last_modified_at: 2022-03-01 00:11:41.798937
