id: ADF11B5FC
title: Brief Confession to the Earth Lords
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.787869
  last_modified_at: 2022-03-01 00:11:41.787872
