id: ADF11B5FC
title: Prayer to Gyaltsen Tsemö Pung Gyen
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.795994
  last_modified_at: 2022-03-01 00:11:41.795997
