id: ADF11B5FC
title: A Concise Sang Offering to Tārā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.782581
  last_modified_at: 2022-03-01 00:11:41.782605
