id: ADF11B5FC
title: Prayer to the Lion of Speech
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:11:41.797824
  last_modified_at: 2022-03-01 00:11:41.797828
